services:
  mongodb:
    image: mongo:latest
    container_name: ensah_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build:
      context: .
      dockerfile: Image/Dockerfile
    image: ensah_chatbot
    container_name: ensah_backend
    restart: always
    ports:
      - "8000:8000"
    entrypoint: python
    command: Image/hundler.py
    env_file: Image/.env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
